version: "3.8"

services:
  database:
    image: "postgres:12.3"
    ports:
      - 5433:5432
    container_name: database-project
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: hospital
    volumes:
      - ./app_docker/database_setup/database_schema.sql:/docker-entrypoint-initdb.d/1-database_schema.sql
      - ./app_docker/database_setup/database_populate_place.sql:/docker-entrypoint-initdb.d/2-data_populate_place.sql
      - ./app_docker/database_setup/database_populate.sql:/docker-entrypoint-initdb.d/3-data_populate.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080
    depends_on:
      - "database"

  flaskapp:
    build: ./app
    ports:
      - 5000:5000
    depends_on:
      - "database"
