-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Supplier"
(
    "Supplier_ID" uuid,
    "Supplier_Name" character varying,
    "Supplier_Mail" character varying,
    "Supplier_TelNr" character varying,
    PRIMARY KEY ("Supplier_ID")
);

CREATE TABLE IF NOT EXISTS public."Medicine"
(
    "Medicine_ID" uuid,
    "Medicine_Name" character varying,
    "Medicine_Pricing" money,
    "Medicine_Amount" smallint,
    PRIMARY KEY ("Medicine_ID")
);

CREATE TABLE IF NOT EXISTS public."Medicine_Supplier"
(
    "Medicine_Medicine_ID" uuid,
    "Supplier_Supplier_ID" uuid
);

CREATE TABLE IF NOT EXISTS public."Patient"
(
    "Patient_ID" uuid,
    "Patient_Name" character,
    "Patient_Forename" character,
    "Patient_Sex" character(1),
    "Patient_Birthdate" date,
    "Room_Nr" smallint,
    "Station_Nr" smallint,
    "Adress_ID" uuid,
    PRIMARY KEY ("Patient_ID")
);

CREATE TABLE IF NOT EXISTS public."Patient_Medicine"
(
    "Patient_Patient_ID" uuid,
    "Medicine_Medicine_ID" uuid,
    "Patient_Medicine_Amount" smallint
);

CREATE TABLE IF NOT EXISTS public."Address"
(
    "Address_ID" uuid,
    "Address_Street" character,
    "Address_HNr" character varying,
    "Place_ID" uuid,
    PRIMARY KEY ("Address_ID")
);

CREATE TABLE IF NOT EXISTS public."Place"
(
    "Place_ID" uuid,
    "Place_Name" character varying,
    "Place_Postal_code" character(5),
    PRIMARY KEY ("Place_ID")
);

CREATE TABLE IF NOT EXISTS public."Employee"
(
    "Employee_ID" uuid,
    "Employee_Name" character,
    "Employee_Forename" character,
    "Employee_Birthdate" date,
    "Employee_Salary" money,
    "Employee_Role" character,
    "Address_ID" uuid,
    PRIMARY KEY ("Employee_ID")
);

CREATE TABLE IF NOT EXISTS public."Station"
(
    "Station_Nr" smallint,
    "Station_Name" character,
    "Station_Amount_of_rooms" smallint,
    PRIMARY KEY ("Station_Nr")
);

CREATE TABLE IF NOT EXISTS public."Station_Employee"
(
    "Station_Station_Nr" smallint,
    "Employee_Employee_ID" uuid
);

CREATE TABLE IF NOT EXISTS public."Room"
(
    "Room_Nr" smallint,
    "Room_Size" smallint,
    "Room_isFull" boolean,
    "Station_Nr" smallint,
    CONSTRAINT "PK_Room" PRIMARY KEY ("Room_Nr")
        INCLUDE("Station_Nr")
);

ALTER TABLE IF EXISTS public."Medicine_Supplier"
    ADD FOREIGN KEY ("Medicine_Medicine_ID")
    REFERENCES public."Medicine" ("Medicine_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Medicine_Supplier"
    ADD FOREIGN KEY ("Supplier_Supplier_ID")
    REFERENCES public."Supplier" ("Supplier_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Patient"
    ADD FOREIGN KEY ("Adress_ID")
    REFERENCES public."Address" ("Address_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Patient"
    ADD FOREIGN KEY ("Room_Nr")
    REFERENCES public."Room" ("Room_Nr") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Patient_Medicine"
    ADD FOREIGN KEY ("Patient_Patient_ID")
    REFERENCES public."Patient" ("Patient_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Patient_Medicine"
    ADD FOREIGN KEY ("Medicine_Medicine_ID")
    REFERENCES public."Medicine" ("Medicine_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Address"
    ADD FOREIGN KEY ("Place_ID")
    REFERENCES public."Place" ("Place_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employee"
    ADD FOREIGN KEY ("Address_ID")
    REFERENCES public."Address" ("Address_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Station_Employee"
    ADD FOREIGN KEY ("Station_Station_Nr")
    REFERENCES public."Station" ("Station_Nr") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Station_Employee"
    ADD FOREIGN KEY ("Employee_Employee_ID")
    REFERENCES public."Employee" ("Employee_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room"
    ADD FOREIGN KEY ("Room_Nr")
    REFERENCES public."Station" ("Station_Nr") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

